on:
 workflow_run:
   workflows: ["R-CMD-check"]
   types: [completed]

name: test-coverage

jobs:
  on-success:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
          with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
        extra-packages: covr

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
